apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
images:
- digest: sha256:b2e35914adcc0680902308a0f296dbf1cde5da3e75712a58f5fc25e3960d6ed9
  name: myapp-test
  newName: harbor.shared.lab.pksdemo.net/library/myapp-test
resources:
- myapp-test-deploy.yaml
- myapp-test-svc.yaml
