apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-test
images:
- digest: sha256:8dce22c72bec3c24aa04ad8d1821bcc173bba6523cd1d54695cd61b95739864c
  name: myapp-test
  newName: harbor.lab.pksdemo.net/tanzu/apps/myapp-test
resources:
- myapp-test-deploy.yaml
- myapp-test-svc.yaml
