apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-test
images:
- digest: sha256:acf730a38fada53bfcabdae3e44b28d49a375f26eb79fcfec3d35bee1e962da8
  name: myapp-test
  newName: harbor.lab.pksdemo.net/tanzu/tbs/myapp-test
resources:
- myapp-test-deploy.yaml
- myapp-test-svc.yaml
