apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: demo
images:
- digest: sha256:9d7ab1250f41de36aedcb8f5d8b7f2540ab6fd1dbf309352d30492fdf5fdeaf7
  name: myapp-test
  newName: tkg-harborplf.dha-tkgdemo.net/tanzu/apps/myapp-test
resources:
- myapp-test-deploy.yaml
- myapp-test-svc.yaml
