apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-test
images:
- digest: sha256:c34f494eb47a222bd6e88c39cfaf1e56877afe9547a88b76710dac5edb1bbd9a
  name: myapp-test
  newName: harbor.lab.pksdemo.net/tanzu/apps/myapp-test
resources:
- myapp-test-deploy.yaml
- myapp-test-svc.yaml
