apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-test
images:
- digest: sha256:c325391df33b0aa068d1ea43ed13441477e0f9989871a58ddbc5ba70e7cc738e
  name: myapp-test
  newName: harbor.lab.pksdemo.net/tanzu/tbs/myapp-test
resources:
- myapp-test-deploy.yaml
- myapp-test-svc.yaml
