apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: demo
images:
- digest: sha256:59e18cd0e80427138aaf0476531dafdae7d7e66efcf0bbd3bdb40d8a103376d1
  name: myapp-test
  newName: harborplf.dha-tkgdemo.net/tanzu/apps/myapp-test
resources:
- myapp-test-deploy.yaml
- myapp-test-svc.yaml
