apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: demo
images:
- digest: sha256:3b7499f48b8b2e50302757f88981bb5f0b91b90b9c14459b3381b7d0817cb06e
  name: myapp-test
  newName: harborplf.dha-tkgdemo.net/tanzu/apps/myapp-test
resources:
- myapp-test-deploy.yaml
- myapp-test-svc.yaml
