apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
images:
- digest: sha256:76b1022be92687e3f1838faf5f02087723e9614dc0bec03f4e34c004f82c6040
  name: myapp-test
  newName: tkg-harborplf.dha-tkgdemo.net/tanzu/apps/myapp-test
resources:
- myapp-test-deploy.yaml
- myapp-test-svc.yaml
