apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-test
images:
- digest: sha256:3771245e452bc088c1beddb6d51540222ce5f74bc1a347f229ee7452eff81ec9
  name: myapp-test
  newName: harbor.shared.lab.pksdemo.net/tanzu/tbs/myapp-test
resources:
- myapp-test-deploy.yaml
- myapp-test-svc.yaml
