images:
- name: myapp-test
  newName: f14c4b25506b4712306be58d4a872a095a01559c6072ddc163f3a26d81e5fd15
resources:
- myapp-test-deploy.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
