apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: demo
images:
- digest: sha256:8baab078061883cfa41f63760025139a1b669bc3a33e84d0b11e8c8632dd2489
  name: myapp-test
  newName: tkg-harborplf.dha-tkgdemo.net/tanzu/apps/myapp-test
resources:
- myapp-test-deploy.yaml
- myapp-test-svc.yaml
