apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-test
images:
- digest: sha256:96126851c6ef0d14f9db7276d09fa222621d189cb7a28297d92945ce9e6e21b8
  name: myapp-test
  newName: harbor.lab.pksdemo.net/tanzu/apps/myapp-test
resources:
- myapp-test-deploy.yaml
- myapp-test-svc.yaml
