apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp-test
  name: myapp-test-svc
  namespace: demo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp-test
  type: LoadBalancer
