apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp-test
  name: myapp-test-deploy
  namespace: myapp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-test
  template:
    metadata:
      labels:
        app: myapp-test
    spec:
      containers:
      - image: harbor.lab.pksdemo.net/tanzu/tbs/myapp-test@sha256:d0d9763744a86db0bb4c1f6627e1dcaa01be455cec68244d1f1d5d6893c5f0be
        imagePullPolicy: IfNotPresent
        name: myapp-test
